version: '3.4'

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - pgdb-data:/var/lib/postgresql/data

  backend:
    image: fyusufa/ft_transcendence_backend
    expose:
      - 80
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      URL: ${URL}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      JWT_SECRET_KEY: ${BACKEND_JWT_SECRET_KEY}
      WATCH: 0
      DISABLE_AUTHENTICATION: false
      BACKEND_42_UID: ${BACKEND_42_UID}
      BACKEND_42_SECRET: ${BACKEND_42_SECRET}
      BACKEND_SALT_ROUNDS: ${BACKEND_SALT_ROUNDS}
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    image: fyusufa/ft_transcendence_frontend
    ports:
      - ${PROXY_PORT}:80
    environment:
      VITE_DISABLE_AUTHENTICATION: false
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy

volumes:
  pgdb-data:
