version: '3.4'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - pgdb-data:/var/lib/postgresql/data
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql

  backend:
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./dtos:/app/src/dtos
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - db

  frontend:
    environment:
      VUE_APP_BACKEND_HOST: ${FRONTEND_BACKEND_HOST}
      VUE_APP_BACKEND_PORT: ${BACKEND_PORT}
    volumes:
      - ./frontend:/app
      - ./dtos:/app/src/dtos
    depends_on:
      - backend

volumes:
  pgdb-data:
