version: '3.4'

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - pgdb-data:/var/lib/postgresql/data
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql

  backend:
    image: fyusufa/ft_transcendence_backend
    expose:
      - 80
    volumes:
      - ./backend:/tmp/app
      - ./dtos:/tmp/dtos
      - ./tsconfig.json:/tmp/tsconfig.json
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      URL: ${URL}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      JWT_SECRET_KEY: ${BACKEND_JWT_SECRET_KEY}
      WATCH: ${BACKEND_DEBUG}
      DISABLE_AUTHENTICATION: ${DISABLE_AUTHENTICATION}
      BACKEND_42_UID: ${BACKEND_42_UID}
      BACKEND_42_SECRET: ${BACKEND_42_SECRET}
      BACKEND_SALT_ROUNDS: ${BACKEND_SALT_ROUNDS}
    build:
      context: .
      dockerfile: backend/${BACKEND_DOCKERFILE}
      args:
          NODE_IMAGE: ${NODE_IMAGE}
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    image: fyusufa/ft_transcendence_frontend
    ports:
      - ${PROXY_PORT}:80
      # the following port is necessary for vite hot module reload (HMR)
      # - 4443:4443
    volumes:
      - ./frontend:/app
      - ./dtos:/dtos
      - ./tsconfig.json:/tsconfig.json
    environment:
      VITE_DISABLE_AUTHENTICATION: ${DISABLE_AUTHENTICATION}
      VITE_URL: ${URL}
    build:
      context: .
      dockerfile: frontend/${FRONTEND_DOCKERFILE}
      args:
          NODE_IMAGE: ${NODE_IMAGE}
          NGINX_IMAGE: ${NGINX_IMAGE}
          VITE_URL: ${URL}
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy

  adminer:
    image: michalhosna/adminer
    restart: unless-stopped
    ports:
      - 8888:8080
    environment:
      ADMINER_DB: ${DB_NAME}
      ADMINER_DRIVER: pgsql
      ADMINER_PASSWORD: ${DB_PASSWORD}
      ADMINER_SERVER: ${DB_HOST}
      ADMINER_USERNAME: ${DB_USER}
      ADMINER_AUTOLOGIN: 1
    depends_on:
      - db
    profiles: ["adminer"]

volumes:
  pgdb-data:
