version: '3.4'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - pgdb-data:/var/lib/postgresql/data
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql

  backend:
    ports:
      - 8080:3000
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - db

  frontend:
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  pgdb-data:
