# Use postgres/example user/password credentials
version: '3.4'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - pgdb-data:/var/lib/postgresql/data

  adminer:
   image: adminer
   restart: always
   ports:
     - 8888:8080
   depends_on:
     - db

  backend:
    build:
        context: ./backend
        args:
            WATCH: 1
    image: nest
    ports:
      - 8080:3000
    working_dir: /app
    volumes:
        - ./backend:/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      WATCH: ${BACKEND_DEBUG}
    depends_on:
      - db

  frontend:
    build:
        context: ./frontend
        target: ${FRONTEND_TARGET:-production}
    image: vue
    ports:
      - 8000:80
    volumes:
        - ./frontend:/app
    depends_on:
      - db

volumes:
  pgdb-data:
