version: '3.4'

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - pgdb-data:/var/lib/postgresql/data

  backend:
    image: fyusufa/ft_transcendence_backend
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    image: fyusufa/ft_transcendence_frontend
    ports:
      - ${FRONTEND_PORT}:80
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  pgdb-data:
