version: '3.4'

services:
  backend:
    build:
      context: .
      dockerfile: backend/${BACKEND_DOCKERFILE}
      args:
          NODE_IMAGE: ${NODE_IMAGE}
          BACKEND_PORT: ${BACKEND_PORT}
    environment:
      WATCH: ${BACKEND_DEBUG}
      DISABLE_AUTHENTICATION: ${DISABLE_AUTHENTICATION}

  frontend:
    ports:
      - 8000:80
    image: fyusufa/ft_transcendence_frontend
    build:
      context: .
      dockerfile: frontend/${FRONTEND_DOCKERFILE}
      args:
          NODE_IMAGE: ${NODE_IMAGE}
          NGINX_IMAGE: ${NGINX_IMAGE}
    environment:
      VUE_APP_DISABLE_AUTHENTICATION: ${DISABLE_AUTHENTICATION}
      VUE_APP_BACKEND_HOST: ${FRONTEND_BACKEND_HOST}
      VUE_APP_BACKEND_PORT: ${BACKEND_PORT}
    profiles: ["frontend"]

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8888:8080
    depends_on:
      - db
    profiles: ["debug"]
