# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - pgdb-data:/var/lib/postgresql/data

  adminer:
   image: adminer
   restart: always
   ports:
     - 8080:8080
   depends_on:
     - db

  backend:
    build: ./backend
    image: tmorris42/test-nest
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    depends_on:
      - db
    
volumes:
  pgdb-data:
