ARG NODE_IMAGE=lts-alpine
FROM node:$NODE_IMAGE
WORKDIR /app
EXPOSE 80
RUN apk update && apk upgrade

COPY ./backend/package*.json ./
RUN npm install && \
	npm upgrade
COPY ./backend/ .
RUN npm install

RUN rm -f ./dtos
COPY ./dtos/ ./src/dtos
COPY ./tsconfig.json ../tsconfig.json

RUN npm run build

HEALTHCHECK --interval=5s --retries=20 CMD wget --spider http://localhost/docs || exit 1

CMD npm run start:prod
