name: backend-tests

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Backend Test and Lint
        run: |
          cd backend
          npm ci
          npm run lint -- --no-fix --max-warnings=0
          npm run test
