name: cd

on:
  push:
    branches: [ master ]

jobs:
  push-image:
    strategy:
      matrix:
        module: [frontend, backend]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check for diff
        id: diff
        continue-on-error: true
        run: |
          git diff ${{ github.event.before }} --exit-code ${{ matrix.module }} dtos docker-compose.yml > /dev/null
      - name: Set environment variables
        run: |
          cat .env.example | grep -v '^#' >> ${GITHUB_ENV}
          echo "BACKEND_42_UID=${{ secrets.BACKEND_42_UID }}" >> ${GITHUB_ENV}
          echo "BACKEND_42_SECRET=${{ secrets.BACKEND_42_SECRET }}" >> ${GITHUB_ENV}
          echo "BACKEND_JWT_SECRET_KEY=${{ secrets.BACKEND_JWT_SECRET_KEY }}" >> ${GITHUB_ENV}
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ${GITHUB_ENV}
      - name: Set up Docker Buildx
        if: ${{ steps.diff.outcome }} == 'failure' }}
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: ${{ steps.diff.outcome }} == 'failure' }}
        uses: docker/login-action@v2
        with:
          username: fyusufa
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Cache Docker layers
        if: ${{ steps.diff.outcome }} == 'failure' }}
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ matrix.module }}-image-${{ github.sha }}
          restore-keys: ${{ matrix.module }}-image-
      - name: Build containers
        if: ${{ steps.diff.outcome }} == 'failure' }}
        run: |
          docker buildx bake --set *.cache-from="type=local,src=/tmp/.buildx-cache" --set *.cache-to="type=local,dest=/tmp/.buildx-cache-new,mode=max" --file docker-compose.yml ${{ matrix.module }} --load
      - name: Move cache
        if: ${{ steps.diff.outcome }} == 'failure' }}
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Push images to Dockerhub
        if: ${{ steps.diff.outcome }} == 'failure' }}
        run: |
          docker image push fyusufa/ft_transcendence_${{ matrix.module }}:latest
