on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
    outputs:
      status:
        value: ${{ jobs.early-exit.steps.dockerhub.outcome == 'success' && jobs.early-exit.steps.diff.outcome == 'success' }}


#${{ jobs.early-exit.outputs.output }}

jobs:
  early-exit:
    runs-on: ubuntu-latest
    #outputs:
      #output: ${{ steps.dockerhub.outcome == 'success' && steps.diff.outcome == 'success' }}
    timeout-minutes: 5
    steps:
      - name: Check if there exists a pushed image
        id: dockerhub
        continue-on-error: true
        run: |
          curl -sf -H "Content-Type: application/json" https://hub.docker.com/v2/repositories/fyusufa/ft_transcendence_${{ inputs.module }}/tags/latest > /dev/null
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check for diff
        id: diff
        continue-on-error: true
        # docker-compose.prod.yml is not checked for a diff because it is not used in the CI, only in a deployment
        run: |
          git diff origin/master --exit-code ${{ inputs.module }} dtos docker-compose.yml .github > /dev/null
