name: frontend

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ ci ]

  workflow_dispatch:

jobs:
  early-exit:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.dockerhub.outcome == 'success' && steps.diff.outcome == 'success' }}
    timeout-minutes: 5
    steps:
      - name: Check if there exists a pushed image
        id: dockerhub
        continue-on-error: true
        run: |
          curl -sf -H "Content-Type: application/json" https://hub.docker.com/v2/repositories/fyusufa/ft_transcendence_frontend/tags/latest > /dev/null
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check for diff
        id: diff
        continue-on-error: true
        run: |
          git diff origin/master --exit-code frontend/src > /dev/null

  build:
    runs-on: ubuntu-latest
    needs: early-exit
    if: needs.early-exit.outputs.status == 'false'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Read environment file
        run: |
          cat .env.example | grep -v '^#' >> ${GITHUB_ENV}
      - uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      - name: Test and Lint
        run: |
          cd frontend
          #TODO: add a --max-warning=0
          npm run lint -- --no-fix
          #TODO: npm run test:unit
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: docker-images
      - name: Build Containers
        # a bug recently fixed in docker buildx does not let one use multiple docker-compose files, see https://github.com/docker/buildx/issues/1172
        #run: docker buildx bake --set *.cache-from="type=local,src=/tmp/.buildx-cache" --set *.cache-to="type=local,dest=/tmp/.buildx-cache-new" --file docker-compose.yml --file docker-compose.override.yml --load
        run: |
          COMPOSE_FILE=docker-compose.yml:docker-compose.override.yml:./.github/docker-compose.ci.yml docker-compose config > docker-compose.bake.yml
          docker buildx bake --set *.cache-from="type=local,src=/tmp/.buildx-cache" --set *.cache-to="type=local,dest=/tmp/.buildx-cache-new" --file docker-compose.bake.yml --load
      # TODO
      #- name: E2E Test
        #run: |
          #npm run test:e2e
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Push image to Dockerhub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u fyusufa --password-stdin
          docker image tag ft_transcendence_frontend fyusufa/ft_transcendence_frontend:latest
          docker image push fyusufa/ft_transcendence_frontend:latest
